# Generated by Django 3.1.2 on 2020-10-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('Mention', 'Mention'), ('Replies', 'Replies'), ('Retweets', 'Retweets'), ('Likes', 'Likes'), ('Followers', 'Followers'), ('Direct Messages', 'Direct Messages')], max_length=30),
        ),
    ]
