# Generated by Django 3.1.2 on 2020-11-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201101_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_pic',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='profile/cover/'),
        ),
    ]
