# Generated by Django 3.1.2 on 2020-10-30 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtags', models.TextField(max_length=140)),
                ('usecount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hashtag',
                'verbose_name_plural': 'Hashtags',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=280, null=True)),
                ('photos', models.ImageField(blank=True, max_length=1000, null=True, upload_to='tweets/images/')),
                ('gif', models.ImageField(blank=True, max_length=5000, null=True, upload_to='tweets/gifs/')),
                ('videos', models.FileField(blank=True, max_length=100000, null=True, upload_to='tweets/videos/')),
                ('topic', models.CharField(blank=True, max_length=140, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('privacy', models.CharField(choices=[('Everyone', 'Everyone'), ('Followers', 'Followers'), ('mentioned', 'mentioned')], default='Everyone', max_length=50)),
                ('location', models.CharField(blank=True, max_length=140, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
