# Generated by Django 3.1.2 on 2020-11-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_comment_commentreply_likes_mention_retweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
