# Generated by Django 3.1.2 on 2020-11-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_auto_20201104_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='tweet',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='tweet',
            field=models.ManyToManyField(to='tweet.Tweet'),
        ),
    ]
