# Generated by Django 3.1.2 on 2020-11-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0010_auto_20201104_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='tweet',
            field=models.ManyToManyField(blank=True, to='tweet.Tweet'),
        ),
    ]
